import{useEffect,useRef,useState}from'react';import{useGame}from'./store';import{BattleScene}from'./BattleScene';import{resolveParry}from'./domain/v2';
const A='/assets/';
export function App(){const screen=useGame(s=>s.screen);return <main>{screen==='restaurant'?<Restaurant/>:screen==='stages'?<Stages/>:screen==='battle'?<Battle/>:<Result/>}</main>}
function Restaurant(){const go=useGame(s=>s.go);return <section className="page restaurant"><div className="shade"/><header><span className="brand">BLADE VERDICT</span><span>金币 0 ◈</span></header><div className="hero"><p className="eyebrow">深渊餐厅 · 今夜营业</p><h1>刀锋<br/><em>裁决</em></h1><p>狩猎怪物，精准招架，将战利品变成传说料理。</p><button data-testid="explore" onClick={()=>go('stages')}>前往探险板 <b>›</b></button></div><nav><span>🍳 厨房</span><span className="active">⚔ 探险</span><span>▦ 仓库</span></nav></section>}
function Stages(){const start=useGame(s=>s.start),go=useGame(s=>s.go);return <section className="page stages"><header><button className="back" onClick={()=>go('restaurant')}>‹</button><div><small>EXPEDITION BOARD</small><h2>选择讨伐目标</h2></div></header><div className="stage-grid"><article className="stage-card selected"><div className="stage-image corn"><span className="danger">危险度 II</span></div><div><small>荒芜农场 · 第一章</small><h2>暴怒玉米怪</h2><p>攻击迟缓但势大力沉。观察收缩的时机环，在青色窗口触碰攻击判定体。</p><dl><div><dt>推荐</dt><dd>招架训练</dd></div><div><dt>战利品</dt><dd>🌽 玉米粒</dd></div></dl><button data-testid="start" onClick={start}>开始讨伐</button></div></article><article className="stage-card locked"><div className="lock">🔒</div><h3>果冻实验室</h3><p>完成玉米怪讨伐后解锁</p></article></div></section>}
function Battle(){const host=useRef<HTMLDivElement>(null),scene=useRef<BattleScene>(null);const battle=useGame(s=>s.battle),parry=useGame(s=>s.parry),verdict=useGame(s=>s.verdict),finish=useGame(s=>s.finish),msg=useGame(s=>s.lastResult);const[start,setStart]=useState(performance.now()),[progress,setProgress]=useState(0),[target,setTarget]=useState({x:.5,y:.55}),[round,setRound]=useState(0),[mode,setMode]=useState<'parry'|'verdict'>('parry'),[hits,setHits]=useState(0);const battleRef=useRef(battle);battleRef.current=battle;
 useEffect(()=>{if(host.current)scene.current=new BattleScene(host.current);return()=>scene.current?.dispose()},[]);
 useEffect(()=>{if(mode!=='parry')return;const now=performance.now(),pos={x:.22+Math.random()*.56,y:.35+Math.random()*.35};setStart(now);setProgress(0);setTarget(pos);let raf=0;const loop=()=>{const p=(performance.now()-now)/900;setProgress(Math.min(1,p));scene.current?.setRing(p,pos);if(p>=1){parry('Miss');setRound(r=>r+1)}else raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[round,mode]);
 const tap=()=>{if(mode!=='parry')return;const result=resolveParry((performance.now()-start));parry(result);if(result!=='Miss')scene.current?.flashSlash();const next=battleRef.current.meter+(result==='Perfect'?30:result==='Nice'?18:0);if(next>=100)setTimeout(()=>setMode('verdict'),450);else setTimeout(()=>setRound(r=>r+1),400)};
 const cut=()=>{const n=Math.min(4,hits+1);setHits(n);scene.current?.flashSlash()};const judge=()=>{const score=[10,35,67,90,100][hits];verdict(score);setHits(0);setMode('parry');setRound(r=>r+1)};
 useEffect(()=>{if(battle.bossHp<=0||battle.playerHp<=0)setTimeout(finish,600)},[battle.bossHp,battle.playerHp]);
 return <section className="battle"><div ref={host} className="canvas" onPointerDown={mode==='parry'?tap:cut}/><header className="battle-top"><button onClick={()=>useGame.getState().go('stages')}>‹</button><div className="boss"><span>暴怒玉米怪</span><div className="bar bossbar"><i style={{width:`${battle.bossHp/8}%`}}/></div><small>{battle.bossHp} / 800</small></div><span className="pause">Ⅱ</span></header><div className="player-hud"><b>守夜厨师</b><div className="bar"><i style={{width:`${battle.playerHp}%`}}/></div><small>HP {battle.playerHp}/100</small></div><div className="meter"><label>裁决</label><div><i style={{height:`${battle.meter}%`}}/></div></div>{mode==='parry'?<><button aria-label="parry target" className="tap-target" style={{left:`${target.x*100}%`,top:`${target.y*100}%`}} onPointerDown={e=>{e.stopPropagation();tap()}}/><div className="hint">触碰攻击核心 · 青色为 PERFECT</div></>:<div className="verdict-ui"><p>VERDICT PHASE</p><h2>划过弱点，执行裁决</h2><div className="weakpoints">{[0,1,2,3].map(i=><button key={i} className={i<hits?'hit':''} onPointerDown={e=>{e.stopPropagation();cut()}}>✦</button>)}</div><button data-testid="judge" onClick={judge}>落 刃 · {([10,35,67,90,100][hits])} 分</button></div>}<div className="combat-msg">{msg}</div></section>}
function Result(){const b=useGame(s=>s.battle),go=useGame(s=>s.go);const win=b.bossHp<=0;return <section className="page result"><div className="result-card"><small>{win?'HUNT COMPLETE':'EXPEDITION FAILED'}</small><h1>{win?'讨伐成功':'败北'}</h1><div className="seal">{win?'完':'败'}</div><p>{win?'怪物食材已经安全送回餐厅。':'调整呼吸，再次挑战。'}</p><div className="loot"><span>🌽</span><div><b>玉米粒</b><small>{b.loot.reduce((n,x)=>n+x.count,0)||1} 份 · {b.loot[0]?.quality||'Broken'}</small></div></div><button data-testid="home" onClick={()=>go('restaurant')}>返回餐厅</button></div></section>}
